### ISSUE TITLE
Native2Forms :Android.Content.Res.Resources+NotFoundException: Unable to find resource ID #0x1

### ISSUE THREAD

**Issue by MyueX** [xamarin/xamarin-forms-samples#167]
Native to Forms Page ,if the page is ContentPage will work,but change to:

MainPage = new NavigationPage(new MainTabbedPage());

they will will generate an exception

Android.Content.Res.Resources+NotFoundException: Unable to find resource ID #0x1
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in /Users/builder/data/lanes/3511/501e63ce/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12083
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00068] in /Users/builder/data/lanes/3511/501e63ce/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:31
  at Android.App.Activity.OnStart () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.App.Activity.cs:4378
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnStart () [0x00000] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:243
  at Android.App.Activity.n_OnStart (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.App.Activity.cs:4368
  at at (wrapper dynamic-method) System.Object:cba64bc5-84ed-43d2-abe9-082d33027a4f (intptr,intptr)
  at android.content.res.Resources$NotFoundException: Unable to find resource ID #0x1
  at at android.content.res.Resources.getResourceName(Resources.java:2235)
  at at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1059)
  at at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
  at at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
  at at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
  at at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
  at at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.n_onStart(Native Method)
  at at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.onStart(FormsAppCompatActivity.java:120)
  at at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
  at at android.app.Activity.performStart(Activity.java:6253)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
  at at android.app.ActivityThread.-wrap11(ActivityThread.java)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:148)
  at at android.app.ActivityThread.main(ActivityThread.java:5417)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This sample has since been re-written and now works correctly.
