### ISSUE TITLE
EmployeeDirectory 

### ISSUE THREAD

**Issue by lnluis** [xamarin/xamarin-forms-samples#28]
When trying to run EmployeeDirectory sample, I get this following error

var task = Task.Run(async () => { 
                Service = await MemoryDirectoryService.FromCsv("XamarinDirectory.csv"); 
            });
task.Wait();

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at EmployeeDirectoryUI.App.GetMainPage()
   at EmployeeDirectory.WinPhone.MainPage..ctor()

Task's aggregate exception

{System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.IO.Stream> PCLStorage.IFile.OpenAsync(PCLStorage.FileAccess)'.
   at EmployeeDirectory.MemoryDirectoryService.<FromCsv>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at EmployeeDirectory.MemoryDirectoryService.FromCsv(String path)
   at EmployeeDirectoryUI.App.<<GetMainPage>b__0>d__2.MoveNext()}

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

This sample has recently been updated and is working fine.
