### ISSUE TITLE
Issue trying to build Xanimals.

### ISSUE THREAD

**Issue by ChrisMacLeanRQI** [xamarin/xamarin-forms-samples#702]
https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals

### Description
When trying to build the Xanimals project I get the following error:

Error		Failed to generate Java type for class: Google.Android.Material.BottomNavigation.BottomNavigationView/IOnNavigationItemReselectedListenerImplementor due to MAX_PATH: System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\Xamarin Samples\xamarin-forms-samples-master\xamarin-forms-samples-master\UserInterface\Xaminals\Xaminals.Android\obj\Debug\100\android\src\mono\com\google\android\material\bottomnavigation\BottomNavigationView_OnNavigationItemReselectedListenerImplementor.java'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
   at Xamarin.Android.Tasks.GenerateJavaStubs.CreateJavaSources(IEnumerable`1 javaTypes, TypeDefinitionCache cache)	Xaminals.Android			

### Information

- Visual Studio 2019 v16.8.4

  - iOS:  Xamarin.iOS SDK 14.8.0.3
  - Android: Xamarin.Android SDK 11.1.0.26
  
Issue occurs on Build.

**Comment by ChrisMacLeanRQI** [comment]
Never mind.  Found problem.  Pesky Android MAX_PATH error. Shortened the directory path and it fixed it.
