### ISSUE TITLE
[PinchGestureSample] App Crashes on Pinch on Android

### ISSUE THREAD

**Issue by ahmedalejo** [xamarin/xamarin-forms-samples#79]
Ran as is and got the following Exception on pinch
```
An unhandled exception occured.

12-01 19:21:21.929 D/Mono    (29612): DllImport attempting to load: '/system/lib/liblog.so'.
12-01 19:21:21.929 D/Mono    (29612): DllImport loaded library '/system/lib/liblog.so'.
12-01 19:21:21.929 D/Mono    (29612): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
12-01 19:21:21.929 D/Mono    (29612): Searching for '__android_log_print'.
12-01 19:21:21.929 D/Mono    (29612): Probing '__android_log_print'.
12-01 19:21:21.929 D/Mono    (29612): Found as '__android_log_print'.
12-01 19:21:21.945 I/MonoDroid(29612): UNHANDLED EXCEPTION:
12-01 19:21:22.078 I/MonoDroid(29612): Java.Lang.NoSuchMethodError: no method with name='<init>' signature='(Landroid/content/Context;Landroid/view/ScaleGestureDetector$OnScaleGestureListener;Landroid/os/Handler;)V' in class Landroid/view/ScaleGestureDetector;
12-01 19:21:22.078 I/MonoDroid(29612):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
12-01 19:21:22.078 I/MonoDroid(29612):   at Android.Runtime.JNIEnv.GetMethodID (IntPtr kls, System.String name, System.String signature) [0x00066] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:162 
12-01 19:21:22.078 I/MonoDroid(29612):   at Android.Views.ScaleGestureDetector..ctor (Android.Content.Context context, IOnScaleGestureListener listener, Android.OS.Handler handler) [0x000bd] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.ScaleGestureDetector.cs:505 
12-01 19:21:22.078 I/MonoDroid(29612):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].<.ctor>b__26_1 () [0x00035] in <filename unknown>:0 
12-01 19:21:22.078 I/MonoDroid(29612):   at System.Lazy`1[T].CreateValue () [0x00075] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/Lazy.cs:440 
12-01 19:21:22.078 I/MonoDroid(29612):   --- End of managed exception stack trace ---
12-01 19:21:22.078 I/MonoDroid(29612): java.lang.NoSuchMethodError: no method with name='<init>' signature='(Landroid/content/Context;Landroid/view/ScaleGestureDetector$OnScaleGestureListener;Landroid/os/Handler;)V' in class Landroid/view/ScaleGestureDetector;
12-01 19:21:22.078 I/MonoDroid(29612): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onTouch(Native Method)
12-01 19:21:22.078 I/MonoDroid(29612): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onTouch(VisualElementRenderer_1.java:56)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.View.dispatchTouchEvent(View.java:7685)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2395)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:22.078 I/MonoDroid(29612): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_dispatchTouchEvent(Native Method)
12-01 19:21:22.078 I/MonoDroid(29612): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.dispatchTouchEvent(PlatformRenderer.java:70)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:22.078 I/MonoDroid(29612): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2306)
12-01 19:21:22.078 I/MonoDroid(29612): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1575)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2470)
12-01 19:21:22.078 I/MonoDroid(29612): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2254)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.View.dispatchPointerEvent(View.java:7888)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3977)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3861)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5101)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5080)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5179)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.os.MessageQueue.next(MessageQueue.java:125)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.os.Looper.loop(Looper.java:138)
12-01 19:21:22.078 I/MonoDroid(29612): 	at android.app.ActivityThread.main(ActivityThread.java:5365)
12-01 19:21:22.078 I/MonoDroid(29612): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-01 19:21:22.078 I/MonoDroid(29612): 	at java.lang.reflect.Method.invoke(Method.java:511)
12-01 19:21:22.078 I/MonoDroid(29612): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
12-01 19:21:22.078 I/MonoDroid(29612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
12-01 19:21:22.078 I/MonoDroid(29612): 	at dalvik.system.NativeStart.main(Native Method)
An unhandled exception occured.

12-01 19:21:23.734 I/MonoDroid(29612): UNHANDLED EXCEPTION:
12-01 19:21:23.742 I/MonoDroid(29612): Java.Lang.NoSuchMethodError: no method with name='<init>' signature='(Landroid/content/Context;Landroid/view/ScaleGestureDetector$OnScaleGestureListener;Landroid/os/Handler;)V' in class Landroid/view/ScaleGestureDetector;
12-01 19:21:23.742 I/MonoDroid(29612):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
12-01 19:21:23.742 I/MonoDroid(29612):   at Android.Runtime.JNIEnv.GetMethodID (IntPtr kls, System.String name, System.String signature) [0x00066] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:162 
12-01 19:21:23.742 I/MonoDroid(29612):   at Android.Views.ScaleGestureDetector..ctor (Android.Content.Context context, IOnScaleGestureListener listener, Android.OS.Handler handler) [0x000bd] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.ScaleGestureDetector.cs:505 
12-01 19:21:23.742 I/MonoDroid(29612):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].<.ctor>b__26_1 () [0x00035] in <filename unknown>:0 
12-01 19:21:23.742 I/MonoDroid(29612):   at System.Lazy`1[T].CreateValue () [0x00075] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/Lazy.cs:440 
12-01 19:21:23.742 I/MonoDroid(29612):   --- End of managed exception stack trace ---
12-01 19:21:23.742 I/MonoDroid(29612): java.lang.NoSuchMethodError: no method with name='<init>' signature='(Landroid/content/Context;Landroid/view/ScaleGestureDetector$OnScaleGestureListener;Landroid/os/Handler;)V' in class Landroid/view/ScaleGestureDetector;
12-01 19:21:23.742 I/MonoDroid(29612): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onTouch(Native Method)
12-01 19:21:23.742 I/MonoDroid(29612): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onTouch(VisualElementRenderer_1.java:56)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.View.dispatchTouchEvent(View.java:7685)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2395)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.742 I/MonoDroid(29612): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_dispatchTouchEvent(Native Method)
12-01 19:21:23.742 I/MonoDroid(29612): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.dispatchTouchEvent(PlatformRenderer.java:70)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.742 I/MonoDroid(29612): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2306)
12-01 19:21:23.742 I/MonoDroid(29612): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1575)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2470)
12-01 19:21:23.742 I/MonoDroid(29612): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2254)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.View.dispatchPointerEvent(View.java:7888)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3977)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3861)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5101)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5080)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5179)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.os.MessageQueue.next(MessageQueue.java:125)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.os.Looper.loop(Looper.java:138)
12-01 19:21:23.742 I/MonoDroid(29612): 	at android.app.ActivityThread.main(ActivityThread.java:5365)
12-01 19:21:23.742 I/MonoDroid(29612): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-01 19:21:23.742 I/MonoDroid(29612): 	at java.lang.reflect.Method.invoke(Method.java:511)
12-01 19:21:23.742 I/MonoDroid(29612): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
12-01 19:21:23.742 I/MonoDroid(29612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
12-01 19:21:23.742 I/MonoDroid(29612): 	at dalvik.system.NativeStart.main(Native Method)
12-01 19:21:23.742 W/dalvikvm(29612): JNI WARNING: JNI method called with exception pending
12-01 19:21:23.742 W/dalvikvm(29612):              in Lmd5b60ffeb829f638581ab2bb9b1a7f4f3f/VisualElementRenderer_1;.n_onTouch:(Landroid/view/View;Landroid/view/MotionEvent;)Z (Throw)
12-01 19:21:23.742 W/dalvikvm(29612): Pending exception is:
12-01 19:21:23.742 I/dalvikvm(29612): java.lang.NoSuchMethodError: no method with name='<init>' signature='(Landroid/content/Context;Landroid/view/ScaleGestureDetector$OnScaleGestureListener;Landroid/os/Handler;)V' in class Landroid/view/ScaleGestureDetector;
12-01 19:21:23.742 I/dalvikvm(29612):   (raw stack trace not found)
12-01 19:21:23.742 I/dalvikvm(29612): "main" prio=5 tid=1 NATIVE
12-01 19:21:23.742 I/dalvikvm(29612):   | group="main" sCount=0 dsCount=0 obj=0x41c929a0 self=0x41c7fb28
12-01 19:21:23.742 I/dalvikvm(29612):   | sysTid=29612 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=1074374108
12-01 19:21:23.742 I/dalvikvm(29612):   | state=R schedstat=( 0 0 0 ) utm=324 stm=72 core=1
12-01 19:21:23.781 I/dalvikvm(29612):   #00  pc 000012a0  /system/lib/libcorkscrew.so (unwind_backtrace_thread+27)
12-01 19:21:23.781 I/dalvikvm(29612):   #01  pc 0005fd1c  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+35)
12-01 19:21:23.781 I/dalvikvm(29612):   #02  pc 00053ba8  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+303)
12-01 19:21:23.781 I/dalvikvm(29612):   #03  pc 00053c42  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
12-01 19:21:23.781 I/dalvikvm(29612):   #04  pc 00038bba  /system/lib/libdvm.so
12-01 19:21:23.781 I/dalvikvm(29612):   #05  pc 000415d4  /system/lib/libdvm.so
12-01 19:21:23.781 I/dalvikvm(29612):   at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onTouch(Native Method)
12-01 19:21:23.781 I/dalvikvm(29612):   at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onTouch(VisualElementRenderer_1.java:56)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.View.dispatchTouchEvent(View.java:7685)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2395)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.781 I/dalvikvm(29612):   at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_dispatchTouchEvent(Native Method)
12-01 19:21:23.781 I/dalvikvm(29612):   at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.dispatchTouchEvent(PlatformRenderer.java:70)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2091)
12-01 19:21:23.781 I/dalvikvm(29612):   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2306)
12-01 19:21:23.781 I/dalvikvm(29612):   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1575)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.app.Activity.dispatchTouchEvent(Activity.java:2470)
12-01 19:21:23.781 I/dalvikvm(29612):   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2254)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.View.dispatchPointerEvent(View.java:7888)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3977)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3861)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5101)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5080)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5179)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.os.MessageQueue.nativePollOnce(Native Method)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.os.MessageQueue.next(MessageQueue.java:125)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.os.Looper.loop(Looper.java:138)
12-01 19:21:23.781 I/dalvikvm(29612):   at android.app.ActivityThread.main(ActivityThread.java:5365)
12-01 19:21:23.781 I/dalvikvm(29612):   at java.lang.reflect.Method.invokeNative(Native Method)
12-01 19:21:23.781 I/dalvikvm(29612):   at java.lang.reflect.Method.invoke(Method.java:511)
12-01 19:21:23.781 I/dalvikvm(29612):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
12-01 19:21:23.781 I/dalvikvm(29612):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
12-01 19:21:23.781 I/dalvikvm(29612):   at dalvik.system.NativeStart.main(Native Method)
12-01 19:21:23.781 I/dalvikvm(29612): 
12-01 19:21:23.781 E/dalvikvm(29612): VM aborting
12-01 19:21:23.781 E/mono-rt (29612): Stacktrace:
12-01 19:21:23.781 E/mono-rt (29612): 
12-01 19:21:23.781 E/mono-rt (29612):   at <unknown> <0xffffffff>
12-01 19:21:23.781 E/mono-rt (29612):   at (wrapper managed-to-native) object.wrapper_native_0x409f45b5 (intptr,intptr) <IL 0x0002a, 0xffffffff>
12-01 19:21:23.781 E/mono-rt (29612):   at Android.Runtime.JNIEnv.Throw (intptr) [0x00020] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:518
12-01 19:21:23.781 E/mono-rt (29612):   at Android.Runtime.AndroidEnvironment.RaiseThrowable (Java.Lang.Throwable) [0x00011] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/AndroidEnvironment.cs:87
12-01 19:21:23.781 E/mono-rt (29612):   at Android.Runtime.AndroidEnvironment.UnhandledException (System.Exception) [0x0007e] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/AndroidEnvironment.cs:114
12-01 19:21:23.781 E/mono-rt (29612):   at (wrapper dynamic-method) object.9b2ce2e5-d015-4227-b486-c7b5e149748c (intptr,intptr,intptr) <IL 0x00030, 0x0009f>
12-01 19:21:23.781 E/mono-rt (29612):   at (wrapper native-to-managed) object.9b2ce2e5-d015-4227-b486-c7b5e149748c (intptr,intptr,intptr) <IL 0x00029, 0xffffffff>
12-01 19:21:23.781 E/mono-rt (29612): 
12-01 19:21:23.781 E/mono-rt (29612): Attempting native Android stacktrace:
12-01 19:21:23.781 E/mono-rt (29612): 
12-01 19:21:23.781 E/mono-rt (29612):   at dvmAbort+75 [0x409f8cd0]
12-01 19:21:23.781 E/mono-rt (29612):   at ???+267733 [0x409f45d5]
12-01 19:21:23.781 E/mono-rt (29612):   at ???+9128 [0x6b12c3a8]
12-01 19:21:23.781 E/mono-rt (29612): 
12-01 19:21:23.781 E/mono-rt (29612): =================================================================
12-01 19:21:23.781 E/mono-rt (29612): Got a SIGSEGV while executing native code. This usually indicates
12-01 19:21:23.781 E/mono-rt (29612): a fatal error in the mono runtime or one of the native libraries 
12-01 19:21:23.781 E/mono-rt (29612): used by your application.
12-01 19:21:23.781 E/mono-rt (29612): =================================================================
12-01 19:21:23.781 E/mono-rt (29612): 
12-01 19:21:23.781 F/libc    (29612): Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 29612 (me.pinchgesture)
```

==== VS 2015 ====
NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Xamarin   4.0.0.1689 (f860fe4)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Forms Player   1.0
Preview Xamarin.Forms XAML on devices and simulators, with support for data-binding via JSON dummy view models.

Xamarin.Android   6.0.0.34 (3efa14c)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.2.1.51 (3c0ec35)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by davidbritch** [comment]
Set API 19 as minimum Android API.

**Comment by ahmedalejo** [comment]
@davidbritch could you please leave it open

*Set API 19 as minimum Android API.* is simply a work around and is well reported by you.

[Xamarin Forms Officially Support API15+](http://developer.xamarin.com/guides/xamarin-forms/getting-started/installation/)

So this is an issue and not simply a configuration case.

**Comment by davidbritch** [comment]
It's logged separately as a bug in bugzilla (36447), which is what the Forms engineering team works from.

**Comment by blattepop** [comment]
Can we get this information in the official Xamarin.Forms Pinch to Zoom documentation.
I mean, if my project is going to crash under a certain API version, I do want to know firsthand.

**Comment by davidbritch** [comment]
Note added to the doc.
