### ISSUE TITLE
CocoSharp Templates:  PathTooLongException

### ISSUE THREAD

**Issue by MidnightCow2016** [xamarin/xamarin-forms-samples#97]
Hi,

The CocoSharp Templates installed via the VisualStudio ( 2015 Community ) Extensions & Updates tool throw the following error when a project is created in the default ThisPc/Documents/VisualStudio2015/ location:

`
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "CreateAdditionalLibraryResourceCache" task failed unexpectedly.
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at Xamarin.Android.Tools.Files.CopyIfChanged(String source, String destination)
   at Xamarin.Android.Tasks.CreateAdditionalLibraryResourceCache.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	CocosSharpFormsPortable1.Droid			
`

I think other templates within the Xamarin ecosystem are causing similar.  Template project was CocoSharp Game ( Xamarin.Forms Portable ).  Problem fixed by moving project folder to C:\Dev\ so not a huge deal but a bit annoying.

Thanks.

**Comment by Rajneesh360Logica** [comment]
Hi @MidnightCow2016 
Thanks for filing the issue. To overcome this issue as the error says, you have to put your sample application at the location  in which the fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. 

please let me know if I am still missing something.

Thanks..!

**Comment by MidnightCow2016** [comment]
Thanks - does this mean there is some movement starting to happen on Cocosharp? :)
